### ISSUE TITLE
Sign Up Page (Wireframe/Lo-Fi/Hi-Fi)

### ISSUE THREAD

**Issue by King-odysseus** [zuri-training/Fetch_Metadata_Team89_MetaMagic#123]

**Comment by Toluwalopee** [comment]
Metamagic Wireframe Prototype for the Sign Up page (Web)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A29455

Image Below
![Sign Up Page](https://user-images.githubusercontent.com/105246982/183881529-6721ac6d-ec92-41e4-aa9f-9ebda0292ee6.png)
[](url)

**Comment by Toluwalopee** [comment]
Metamagic Low Fidelity Prototype for the Sign Up page (Web)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A27315

Image Below

![Sign up page](https://user-images.githubusercontent.com/105246982/183882354-acf5fab8-b615-4e28-9e60-3f19dbc88a19.png)

**Comment by Toluwalopee** [comment]
Metamagic High Fidelity Prototype for the Sign Up page (Web) (Default and Entered)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A25019

Image Below
![Sign Up Page (Default)](https://user-images.githubusercontent.com/105246982/183883319-bd934cf1-78a4-490c-bc1c-30d151ec6f58.png)
![Sign Up Page (Filled)](https://user-images.githubusercontent.com/105246982/183883337-04807626-0be2-4c4a-afd7-6a09d42724a9.png)
