### ISSUE TITLE
Forgot password page for desktop view (Wireframe)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#152]

**Comment by ADEOLA2822** [comment]
RESULT FOR FORGOT PASSWORD PAGE (WIREFRAME)

Figma link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A29387

Image: 

![Image](https://user-images.githubusercontent.com/105210985/183887022-1c6bc7f6-609f-427f-82bb-5856074fb25a.png)
