### ISSUE TITLE
Sign Up page for desktop (Wireframe)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#158]

**Comment by Toluwalopee** [comment]
Metamagic Wireframe Prototype for the Sign Up page (Web)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A29455

Image Below



![Image](https://user-images.githubusercontent.com/105246982/183929233-38d630d1-7f35-46b6-83be-0690cca5ed3d.png)
