### ISSUE TITLE
Sign Up page for desktop (Lo-Fi)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#159]

**Comment by Toluwalopee** [comment]
Metamagic Low Fidelity Prototype for the Sign Up page (Web)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A27315

Image Below



![Image](https://user-images.githubusercontent.com/105246982/183929600-f9474dc1-b49b-4120-9d36-e0c95c937d14.png)

**Comment by Toluwalopee** [comment]
Metamagic Low Fidelity Prototype for the Sign Up page (Web)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A27315

Image Below



![Image](https://user-images.githubusercontent.com/105246982/183929600-f9474dc1-b49b-4120-9d36-e0c95c937d14.png)
