### ISSUE TITLE
Sign Up page for desktop (Hi-Fi)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#160]

**Comment by Toluwalopee** [comment]
Metamagic High Fidelity Prototype for the Sign Up page (Web) (Default and Entered)
Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A25019

image below


![Image](https://user-images.githubusercontent.com/105246982/183929837-45f83352-901e-4fb4-817c-e3150f30e98d.png)



![Image](https://user-images.githubusercontent.com/105246982/183929889-d843233e-bd32-4d5f-b132-b6b711284996.png)
