### ISSUE TITLE
Sign Up page for mobile (Wireframe)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#161]

**Comment by Toluwalopee** [comment]
Metamagic Wireframe Prototype for the Sign Up page (Mobile View)

Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A16945

Image



![Image](https://user-images.githubusercontent.com/105246982/183930682-f2629df3-eaae-46a0-aba4-8396e6b7f4b9.png)
