### ISSUE TITLE
Sign Up page for mobile(Lo-Fi)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#162]

**Comment by Toluwalopee** [comment]
Metamagic Low Fidelity Prototype for the Sign Up page (Mobile View) Default and Entered

Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A14329

Image



![Image](https://user-images.githubusercontent.com/105246982/183931057-7665d474-fcb1-44a2-b25b-24a2b5cee64a.png)



![Image](https://user-images.githubusercontent.com/105246982/183931128-13a7e075-61cb-4750-8987-ff9e4e052630.png)
