### ISSUE TITLE
Sign Up page for mobile (Hi-Fi)

### ISSUE THREAD

**Issue by Bayolanez** [zuri-training/Fetch_Metadata_Team89_MetaMagic#163]

**Comment by Toluwalopee** [comment]
Metamagic High Fidelity Prototype for the Sign Up page (Mobile View) Default and Entered

Figma Link: https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A11558

Image



![Image](https://user-images.githubusercontent.com/105246982/183931481-f3bfb96e-e90a-4d56-9e61-7c5c733d9fdc.png)



![Image](https://user-images.githubusercontent.com/105246982/183931705-b70597d2-f14d-4ea4-8f3f-e3426c91b035.png)
