### ISSUE TITLE
About us page (Wireframe) Desktop

### ISSUE THREAD

**Issue by Ayodeji100** [zuri-training/Fetch_Metadata_Team89_MetaMagic#94]

**Comment by Ayodeji100** [comment]
**Metamagic About us page (Wireframe) Desktop**

**Link-**
https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A29627

**image**
![About Us Page](https://user-images.githubusercontent.com/105288690/183782017-c76acdc3-f298-4da5-aa79-79fb994360c2.png)

**Comment by Inioluwa001** [comment]
Completed Desktop About us page wireframe

Figma link
https://www.figma.com/file/zVCj2MJ5YTNWGJfwvUvS3P/Team_89-MetaMagic?node-id=2565%3A29627
